# Generated by Django 4.2.8 on 2024-01-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingregdients',
            new_name='ingredients',
        ),
    ]
