# Generated by Django 4.2.8 on 2024-01-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='content',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
    ]
