# Generated by Django 4.2.8 on 2024-01-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_recipe_servings_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='author',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_on',
        ),
    ]
