# Generated by Django 4.2.8 on 2024-01-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_body_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
